name: Karate UI Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('swaglab/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Maven
        run: |
          mvn --version

      - name: Start Web Server
        run: |
          # Command to start your web server
          nohup java -jar swaglab/target/my-webserver.jar &

      - name: Wait for Web Server to be Ready
        run: |
          # Wait for the web server to be up and running
          until curl -s http://localhost:9222; do
            echo "Waiting for web server..."
            sleep 5
          done

      - name: Install dependencies
        run: mvn clean install -DskipTests
        working-directory: swaglab 

      - name: Run Karate Tests
        run: |
          mvn test -Dtest=TestEntireFlowRunner

      - name: Upload Surefire Test Report
        if: always()  # Always run this step
        uses: actions/upload-artifact@v2
        with:
          name: surefire-test-report
          path: swaglab/target/surefire-reports

      - name: Generate Karate Test Report
        if: always()  # Always run this step
        run: |
          mkdir -p karate-reports
          cp -r swaglab/target/karate-reports/* karate-reports/
        
      - name: Upload Karate Test Report
        if: always()  # Always run this step
        uses: actions/upload-artifact@v2
        with:
          name: karate-test-report
          path: karate-reports
